# Generated by Django 5.0.6 on 2024-05-28 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_alter_sala_capacidade_alter_usuario_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='data',
            new_name='data_fim',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='logo',
            field=models.ImageField(upload_to='Logo/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='imagem',
            field=models.ImageField(upload_to='imgHome/'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='foto',
            field=models.ImageField(upload_to='imgSala/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_user',
            field=models.ImageField(upload_to='imgUser/'),
        ),
    ]
