# Generated by Django 5.0.6 on 2024-06-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0003_rename_data_agendamento_data_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='equipamento',
        ),
    ]
