# Generated by Django 5.0.6 on 2024-06-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0004_remove_sala_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='corredor',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
