# Generated by Django 5.0.6 on 2024-06-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0005_sala_corredor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_user',
            field=models.ImageField(default='imgUser/default.jpg', upload_to='imgUser/'),
        ),
    ]
