# Generated by Django 5.0.6 on 2024-06-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0006_alter_usuario_cpf_alter_usuario_foto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
