# Generated by Django 5.0.6 on 2024-06-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0007_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
