# Generated by Django 5.0.6 on 2024-06-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0008_remove_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='foto',
            field=models.ImageField(default='imgSala/saladefault.png', upload_to='imgSala/'),
        ),
    ]
