# Generated by Django 5.0.6 on 2024-06-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0009_alter_sala_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='foto',
            new_name='foto_sala',
        ),
    ]
