# Generated by Django 5.0.6 on 2024-06-13 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0011_remove_agendamento_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='hora_fim',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='assunto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='turma',
            field=models.CharField(max_length=30),
        ),
    ]
