# Generated by Django 5.0.6 on 2024-06-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0012_agendamento_hora_fim_agendamento_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
